version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: mongoose
    versions:
    - "> 5.9.20"
  - dependency-name: "@sentry/node"
    versions:
    - 6.2.1
    - 6.2.2
    - 6.2.4
    - 6.2.5
    - 6.3.0
  - dependency-name: redis-modules-sdk
    versions:
    - 0.4.5
    - 0.4.7
    - 0.5.1
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.22.0
    - 7.24.0
  - dependency-name: i18next
    versions:
    - 19.8.6
    - 19.8.8
    - 19.9.0
    - 19.9.1
    - 19.9.2
    - 20.0.0
    - 20.2.1
  - dependency-name: discord.js
    versions:
    - 12.5.2
  - dependency-name: markdown-table
    versions:
    - 3.0.0
